-- V11__seed_data.sql
-- Dev seed data — all passwords are Test1234!
-- BCrypt hash generated by running HashGeneratorTest (cost factor 10)

-- ── Users ─────────────────────────────────────────────────────────────────────
INSERT INTO users (username, email, password) VALUES
    ('alex_lead',   'alex@example.com',   '$2a$10$7KG/BHjLrnSBBQjttN3z8.sV9sYH7ZQurkeNNKcVvQRfHYMKnKohS'),
    ('sam_dev',     'sam@example.com',    '$2a$10$7KG/BHjLrnSBBQjttN3z8.sV9sYH7ZQurkeNNKcVvQRfHYMKnKohS'),
    ('jordan_free', 'jordan@example.com', '$2a$10$7KG/BHjLrnSBBQjttN3z8.sV9sYH7ZQurkeNNKcVvQRfHYMKnKohS');

-- ── Projects ──────────────────────────────────────────────────────────────────
INSERT INTO projects (name, description, owner_id) VALUES
    ('TaskFlow Demo', 'Sample project for development',
     (SELECT id FROM users WHERE username = 'alex_lead')),
    ('API Design',    'REST API design and documentation',
     (SELECT id FROM users WHERE username = 'alex_lead'));

-- ── Project members ───────────────────────────────────────────────────────────
INSERT INTO project_members (project_id, user_id, role) VALUES
    ((SELECT id FROM projects WHERE name = 'TaskFlow Demo'),
     (SELECT id FROM users WHERE username = 'alex_lead'),   'OWNER'),
    ((SELECT id FROM projects WHERE name = 'TaskFlow Demo'),
     (SELECT id FROM users WHERE username = 'sam_dev'),     'MEMBER'),
    ((SELECT id FROM projects WHERE name = 'TaskFlow Demo'),
     (SELECT id FROM users WHERE username = 'jordan_free'), 'MEMBER'),
    ((SELECT id FROM projects WHERE name = 'API Design'),
     (SELECT id FROM users WHERE username = 'alex_lead'),   'OWNER');

-- ── Tasks (6 in TaskFlow Demo, all 4 columns covered) ─────────────────────────
INSERT INTO tasks (title, status, priority, project_id, assignee_id, created_by) VALUES
    ('Set up authentication', 'TODO', 'HIGH',
     (SELECT id FROM projects WHERE name = 'TaskFlow Demo'),
     (SELECT id FROM users WHERE username = 'alex_lead'),
     (SELECT id FROM users WHERE username = 'alex_lead')),

    ('Design kanban UI mockups', 'TODO', 'MEDIUM',
     (SELECT id FROM projects WHERE name = 'TaskFlow Demo'),
     (SELECT id FROM users WHERE username = 'sam_dev'),
     (SELECT id FROM users WHERE username = 'alex_lead')),

    ('Implement database schema', 'IN_PROGRESS', 'HIGH',
     (SELECT id FROM projects WHERE name = 'TaskFlow Demo'),
     (SELECT id FROM users WHERE username = 'sam_dev'),
     (SELECT id FROM users WHERE username = 'alex_lead')),

    ('Code review login module', 'IN_REVIEW', 'MEDIUM',
     (SELECT id FROM projects WHERE name = 'TaskFlow Demo'),
     (SELECT id FROM users WHERE username = 'alex_lead'),
     (SELECT id FROM users WHERE username = 'sam_dev')),

    ('Set up project repository', 'DONE', 'LOW',
     (SELECT id FROM projects WHERE name = 'TaskFlow Demo'),
     (SELECT id FROM users WHERE username = 'alex_lead'),
     (SELECT id FROM users WHERE username = 'alex_lead')),

    ('Write API documentation', 'DONE', 'MEDIUM',
     (SELECT id FROM projects WHERE name = 'TaskFlow Demo'),
     (SELECT id FROM users WHERE username = 'jordan_free'),
     (SELECT id FROM users WHERE username = 'alex_lead'));

-- ── Labels ────────────────────────────────────────────────────────────────────
INSERT INTO labels (name, color, project_id) VALUES
    ('frontend', '#3B82F6', (SELECT id FROM projects WHERE name = 'TaskFlow Demo')),
    ('backend',  '#10B981', (SELECT id FROM projects WHERE name = 'TaskFlow Demo')),
    ('bug',      '#EF4444', (SELECT id FROM projects WHERE name = 'TaskFlow Demo'));

-- ── Task labels ───────────────────────────────────────────────────────────────
INSERT INTO task_labels (task_id, label_id) VALUES
    ((SELECT id FROM tasks WHERE title = 'Set up authentication'),
     (SELECT id FROM labels WHERE name = 'backend'
       AND project_id = (SELECT id FROM projects WHERE name = 'TaskFlow Demo'))),

    ((SELECT id FROM tasks WHERE title = 'Design kanban UI mockups'),
     (SELECT id FROM labels WHERE name = 'frontend'
       AND project_id = (SELECT id FROM projects WHERE name = 'TaskFlow Demo'))),

    ((SELECT id FROM tasks WHERE title = 'Implement database schema'),
     (SELECT id FROM labels WHERE name = 'backend'
       AND project_id = (SELECT id FROM projects WHERE name = 'TaskFlow Demo'))),

    ((SELECT id FROM tasks WHERE title = 'Code review login module'),
     (SELECT id FROM labels WHERE name = 'backend'
       AND project_id = (SELECT id FROM projects WHERE name = 'TaskFlow Demo')));

-- ── Comments ──────────────────────────────────────────────────────────────────
INSERT INTO comments (content, task_id, author_id) VALUES
    ('Database schema looks good, just need to add the indexes.',
     (SELECT id FROM tasks WHERE title = 'Implement database schema'),
     (SELECT id FROM users WHERE username = 'alex_lead')),

    ('Working on the Flyway migrations now.',
     (SELECT id FROM tasks WHERE title = 'Implement database schema'),
     (SELECT id FROM users WHERE username = 'sam_dev')),

    ('Looks good to me. Just fix the typo on line 12.',
     (SELECT id FROM tasks WHERE title = 'Code review login module'),
     (SELECT id FROM users WHERE username = 'alex_lead'));
